### ISSUE TITLE
Image placement/size on sample news articles

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet.prototype#102]
Is the image placement/size correct in the prototype?

![prototype news image placement](https://cloud.githubusercontent.com/assets/2538526/8396213/cd259fde-1d94-11e5-8855-ba2887f045e7.png)

It looks to me like the image should be centralised, or wider.

**Comment by cornae** [comment]
Yes, it’s a design gimmick. I was thinking that it maybe has a little bit too much character for na off he shelf design. I’m curious to see it with real content and make some tweaks then if it feels wrong.
