### ISSUE TITLE
People selector resizing oddity on social posting widget

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet.prototype#103]
After I select Guido in the people selector list on the social posting widget:

![screen shot 2015-06-28 at 13 06 20](https://cloud.githubusercontent.com/assets/2538526/8396262/c96c5b56-1d96-11e5-9394-ff031bfb391d.png)

the 'inside' of the people selector appears to shift left/get wider:

![screen shot 2015-06-28 at 13 06 27](https://cloud.githubusercontent.com/assets/2538526/8396261/c3f0f25e-1d96-11e5-809a-6d431ce89e36.png)

**Comment by cornae** [comment]
This one is known to me as one of the bugs in the Gecko CSS engine. So Firefox I assume? The ignored left padding in the search box is also a Gecko engine bug making the search icon render on top of the text. I can put it on my FF, which I open now and then when I feel brave ;).
