### ISSUE TITLE
Starting a second search breaks the search faceting

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet.prototype#106]
Just found a regression in the search prototype. Replicate as follows:

* Load http://prototype.ploneintranet.net/
* 'Log in'
* Type something in the search box in the header
* Interact with the search facets on the left-hand-side. You should see that the facet options remain whilst the results on the right update. (This is correct)
* Start a *new* search by typing in the main search box or just clicking the magnifier icon
* Now when you interact with the facets, the entire bottom half of the page reloads, resetting you facet choices.

Unfortunately this renders the search unusable until you manually refresh the entire page, or start from scratch using the search box in header.

**Comment by mattss** [comment]
fyi @cornae / @jcbrand as far as I can tell, this started happening after the 'all/none' fix was made for #95

**Comment by cornae** [comment]
Doesn't sound like something I should look at right? No-one is assigned, which makes me worried it's not going to be picked up.

**Comment by mattss** [comment]
@pilz mentioned that @jcbrand should be able to look at this next week.

**Comment by mattss** [comment]
Resolved by https://github.com/ploneintranet/ploneintranet/pull/375
