### ISSUE TITLE
Masonry doesn't update after injection

### ISSUE THREAD

**Issue by cornae** [ploneintranet/ploneintranet.prototype#126]
On the dashboard there's a contacts portlet. When you type something its search field, it injects a result. This influences the layout. Masonry doesn't update after that, so two portliest now overlap.

What I would like is that when any layout modifier — including injection — is active within the container of masonry, that masonry recalcs.

**Comment by cornae** [comment]
I just found that on my laptop it DOES update after injection. Apparently i have ran 'make designerhappy' on this computer more recently than on the other and has the problem been fixed in the mean time and I didn't know about it. Could this be?

**Comment by jcbrand** [comment]
Yes, this has and should be fixed.

**Comment by pilz** [comment]
cool, so this is actually done.
