### ISSUE TITLE
Expanded Sidebar for Tasks/Events

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet.prototype#128]
We show additional metadata for the item selector. Now we could also do that for Tasks and Events.
Tasks: Show assignee, tags and deadline
Events: Show invitees, Attachments

**Comment by pilz** [comment]
Updated the events markup in https://github.com/ploneintranet/ploneintranet/pull/730

**Comment by pilz** [comment]
When you are about to fully refactor, can we also have a separation in open/planned and done tasks?

**Comment by cornae** [comment]
That could be one of the grouping options…
