### ISSUE TITLE
Workcase title: display overlay when scrolling

### ISSUE THREAD

**Issue by angeldasangel** [ploneintranet/ploneintranet.prototype#130]
When scrolling in right content area in a Workcase, the title is overlaying the description label. Not sure, but I think the used browser is Internet Explorer (could not reproduce in Chrome or Firefox).

Happens for Tasks, Events and Documents.

![bug 12106 - scrollfehler](https://cloud.githubusercontent.com/assets/2470824/9194925/319a5b56-401f-11e5-87ed-328a81021d1d.png)

**Comment by pilz** [comment]
Happens in FF and IE

**Comment by pilz** [comment]
Fixed, thx @cornae !

**Comment by cornae** [comment]
Note: the text might look more 'fat' in IE and FF. There's nothing I can do about that at the moment. It's either more fat text, or loosing the caret until IE and FF support the full CSS 3 spec.
