### ISSUE TITLE
Post box: sroll-problem with long texts in post form

### ISSUE THREAD

**Issue by angeldasangel** [ploneintranet/ploneintranet.prototype#131]
When typing a text longer than 3 lines into the textarea of the post box, the text can not be scrolled and so the lower lines cannot be seen

![2c528568-3c43-11e5-9f01-79c922db6333](https://cloud.githubusercontent.com/assets/2470824/9220959/ae9b6fd8-40e6-11e5-830d-8853bc383f23.png)

**Comment by cornae** [comment]
Scrolling cannot be done with content mirror. We could either let it auto grow, or cap the max chars at a safe value. I would like to try auto grow, but it requires some refactoring of the SCSS of the current component. Before I start that not so small task, I would like to confirm with @jcbrand if pat-masonry also listens to pat-content-mirror as a layout modifier and if not if that can easily be added.

**Comment by jcbrand** [comment]
pat-content-mirror doesn't trigger any events, so there's nothing for pat-masonry to listen to. It's also not a core pattern (it's in it's own repo).

We can make pat-content-mirror trigger a *pat-update* event and let pat-masonry listen to that.

**Comment by cornae** [comment]
Sounds good?

**Comment by pilz** [comment]
Confirm works
