### ISSUE TITLE
Larger "group by" (through translation) is not fully clickable anymore

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet.prototype#132]
![bildschirmfoto 2015-08-12 um 18 29 03](https://cloud.githubusercontent.com/assets/138906/9229980/1deed620-4120-11e5-9072-6b902a8e16c2.png)

If the "Group by" gets translated and thereby gets longer (i.e. "Gruppieren nach"), only the part that is as long as the original "Group by folder" text is clickable. The characters afterwards are no longer.

**Comment by cornae** [comment]
Most peculiar. It's designed so that it should grow with any text length and that's what it does for me. Is it in a specific browser where this happens?

**Comment by pilz** [comment]
Probably FF only

**Comment by cornae** [comment]
Extra line off CSS added for Gecko now.
