### ISSUE TITLE
Too many lines in post comment don't scroll

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet.prototype#135]
<img width="1012" alt="bildschirmfoto 2015-08-19 um 12 42 04" src="https://cloud.githubusercontent.com/assets/138906/9354316/c8ba39f6-466f-11e5-812e-c0259c6ca6db.png">

**Comment by cornae** [comment]
Related to issue #131

**Comment by pilz** [comment]
Confirm works
