### ISSUE TITLE
Title Text duplication

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet.prototype#146]
<img width="1280" alt="bildschirmfoto 2015-09-10 um 16 32 40" src="https://cloud.githubusercontent.com/assets/138906/9791095/ad88381a-57d9-11e5-9959-527dba9a34d1.png">

@cornae Do you happen to remember the fix you did for FF in the comments fields of the stream? Seems we have a very similar issue for titles that are longer than the space available until it reaches the buttons.

**Comment by cornae** [comment]
Should be good now

**Comment by pilz** [comment]
Confirmed fixed. Triggered new fun in #147.
