### ISSUE TITLE
Prototype issues: event form

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet.prototype#150]
![bildschirmfoto 2015-09-17 um 09 58 41](https://cloud.githubusercontent.com/assets/138906/9927959/c7d0c0b8-5d22-11e5-9fac-3dbcd640cf51.png)

1. event form needs the change to the textarea title field
2. the date fields are not big enough to contain a full date.

**Comment by cornae** [comment]
Both done.
