### ISSUE TITLE
Dashboard: order of tiles different in IE 10

### ISSUE THREAD

**Issue by angeldasangel** [ploneintranet/ploneintranet.prototype#151]
The tiles on dashboard are displayed in a different order in IE 10 than in reference browser (Chrome).

All fine in IE 11.

See on https://stagingikath.zhkath.ch/ in both views (Startseiten-Ansicht and Cockpit-Ansicht)
User test.weber

Dashboard in IE 10:
![windows_8_internet_explorer_10_1280x1024_window](https://cloud.githubusercontent.com/assets/2470824/9945636/ad6d0490-5d8e-11e5-8cb0-0e0be6d5dd5f.png)
Dashboard in Chrome:
![windows_8_google_chrome_44_1280x1024_window](https://cloud.githubusercontent.com/assets/2470824/9945638/b18786b8-5d8e-11e5-9045-6170ecef61ec.png)

**Comment by angeldasangel** [comment]
Dashboard task centric view is also different in prototype:

IE10:
![tiles_order_dashboard2_ie10](https://cloud.githubusercontent.com/assets/2470824/10132430/b16b273e-65d6-11e5-8750-2efc01c594f8.png)


Chrome:
![screen shot 2015-09-28 at 11 36 59](https://cloud.githubusercontent.com/assets/2470824/10132433/b6089628-65d6-11e5-9b88-1ebf6e59c1e7.png)

**Comment by cornae** [comment]
Masonry seems to make slightly different choices in IE which I don't think I can influence. The issue with the timeline not being shown on the right in the content centric view is worrisome. It seems that 'stamping' — a feature of masonry — is not picked up here. @jcbrand, Any idea if this is a .js issue in the Pattern?

**Comment by jcbrand** [comment]
Not sure what the issue might be here. If the problem is still there after my recent IE10 fix, then I'll have to investigate this one.

**Comment by cornae** [comment]
Actually, I don’t get the issue in IE10 :). Was your fix a very general one and not strictly related to pat-switch/inject?

**Comment by jcbrand** [comment]
@cornae yes, it was a more general fix. So various things that were broken might now be working :)
