### ISSUE TITLE
Extend sidebar link does not work in IE 10

### ISSUE THREAD

**Issue by angeldasangel** [ploneintranet/ploneintranet.prototype#156]
In IE 10: the link to extend the sidebar does not work (nothing happens).

Works fine in IE 11.

**Comment by cornae** [comment]
Works for me in IE10 mode in IE11 so I guess it's a .js issue. Moving to @jcbrand to research if that's the case.

**Comment by jcbrand** [comment]
Fixed.

Change is here: https://github.com/Patternslib/Patterns/commit/334b64957da88296b57be8d3b22726566abd8b00

And pull request for PI is here: https://github.com/Patternslib/Patterns/commit/334b64957da88296b57be8d3b22726566abd8b00

**Comment by cornae** [comment]
Great. How do I get it in proto? Just run make?

**Comment by jcbrand** [comment]
@cornae: make clean and then make should do it.

**Comment by cornae** [comment]
Thanks, works perfectly. We have a great process flow ;)
