### ISSUE TITLE
Editor buttons clearFormatting and viewSource

### ISSUE THREAD

**Issue by reinhardt** [ploneintranet/ploneintranet.prototype#160]
We would like to add the buttons clearFormatting and viewSource to the editor and need styling/icons for them in the CSS (.raptor-ui-clear-formatting and .raptor-ui-view-source (?)).

**Comment by cornae** [comment]
I don’t see a need for either of those. Can you tell me where this requirement comes from?

**Comment by reinhardt** [comment]
Good that you asked. I've discussed it with @pilz again and we found that the wish to have clearFormatting stems from an assumption that is not valid any more. viewSource is intended as a debugging and quick intervention tool for us, but we don't actually need an icon for that because we don't need to show it to regular users.

So, great to have talked about it, and please forget all about it for now. :-) And sorry for bothering you without thinking it through completely.

**Comment by cornae** [comment]
I’m glad I asked ;)
