### ISSUE TITLE
display problems on ipad

### ISSUE THREAD

**Issue by angeldasangel** [ploneintranet/ploneintranet.prototype#169]
some users reported different problems they have with the ikath page on ipad:

-------------------

Das Responsive-Design für Arbeitsräume auf ipad funktioniert noch nicht. Es wird ein übergrosser Ausschnitt aus dem Arbeitsraum angezeigt, man kann sich so nicht zurechtfinden.

Responsive-Design for Workspaces does not work on ipad yet. A oversized cutout of the workspace is displayed, one cannot orient oneself.

-------------------

kleiner Fehler auf Ipad, Suchfeld abgeschnitten (see attached image)

Small error on ipad: searchfield cut (see image)
![ikath_searchfield_ipad](https://cloud.githubusercontent.com/assets/2470824/10370752/99e7ae54-6de0-11e5-9d60-36b33c4bf1a2.png)

**Comment by cornae** [comment]
The first issue i don't recognise. Please images and tap paths to reproduce in a separate tickets. I can't pick up or priorities umbrella tickets. It could be that this is about ticket #161. For which I had an additional question to @pilz which remained unanswered. 

The second issue, is it iKath style specific? In the standard style it looks at least good on my iPad. a

**Comment by cornae** [comment]
Looking at your screengrab again, what browser is that? It looks very non-standard. I took it that we support iOS with its default browser. Do we need to support other browsers than Safari?

**Comment by angeldasangel** [comment]
Hi Cornelis, 

cannot reproduce the first issue with IOS Simulator for iPad 2 or iPad Air. So we skip this for now.
The look of the searchfield (cut) can be reproduced by rotating the iPad to portrait format. But we support landscape format for tablets, so we will skip this for now as well. 

Thanks a lot, Angel

**Comment by angeldasangel** [comment]
Seems all to be fixed. Thanks!
