### ISSUE TITLE
Documentation of pat-autosuggest

### ISSUE THREAD

**Issue by jcbrand** [ploneintranet/ploneintranet.prototype#23]
_From @cornae on March 13, 2015 9:30_

Documentation pat-autosuggest is missing. Need to know ate least which properties I can use :).

_Copied from original issue: ploneintranet/ploneintranet#9_

**Comment by gyst** [comment]
https://github.com/Patternslib/Patterns/blob/master/src/pat/auto-suggest/documentation.md
