### ISSUE TITLE
pat-bumper with other sides than top

### ISSUE THREAD

**Issue by jcbrand** [ploneintranet/ploneintranet.prototype#24]
_From @cornae on March 12, 2015 19:13_

The new pat-bumper doesn't seem to respond to other sides that the top the parent it should bump against. For the comment trails underneath documents I need it to work also when you scroll down.

_Copied from original issue: ploneintranet/ploneintranet#6_

**Comment by jcbrand** [comment]
_From @fulv on March 24, 2015 15:55_

@cornae says: 
i was thinking:

bump-side: top left right bottom

cornelis [08:52]
default = top

cornelis [08:52]
like now

cornelis [08:52]08:52
but you can combine multiple

**Comment by jcbrand** [comment]
_From @adrianwhite on March 24, 2015 16:11_

So if it has all four then it is always within frame?

**Comment by jcbrand** [comment]
_From @cornae on March 25, 2015 11:39_

Correct. Then it has no escape.

**Comment by fulv** [comment]
@cornae, I think it's already doing what you want.  If you go to the http://patternslib.com/demo/bumper/index.html page and reduce the height of the browser window, the demo bar will bump against both the top and the bottom edge.  Even the right edge, but if you shrink the width of the window there will be so many other issues with the css, it's hard to tell what is actually going on.  But you see the .bumped-right class being applied and removed.
Of course, it's possible that the code in ploneintranet is a different version than the one on the patternslib demo site, I'm not sure.

If you disagree, please point me to an example I can reproduce, if possible in the prototype.

**Comment by cornae** [comment]
What you're looking at is the old pat-bumper. That's why I mentioned the problem is in the new pat-bumper. It's a totally rewritten pat-bumper that works also entirely different from it's predecessor.

**Comment by fulv** [comment]
@cornae Where are you looking at the new pat-bumper?  Point me to something I can reproduce.

**Comment by cornae** [comment]
http://patternslib.syslab.com/bumper/ has the newer version that we also use in PI. It doesn't have very inspring CSS yet though, but you can see how it works with position relative.

**Comment by fulv** [comment]
@cornae, I've spent the entire weekend debugging this, and I'm nowhere closer to fixing it.  The demo at http://patternslib.syslab.com/bumper/ is actually broken:  it has two `pat-bumper`, only one of which works.  The element `div.pat-bumper.message.info` does not work, while the element `p.pat-bumper.message.info` does work.   In particular, the container for the `div` has a `scroll` event handler registered, but it never fires.
I thought it might have to do with injection, so I constructed my own demo page, but that did not get me any closer.

For the record, I did not know there was a "new" pat-bumper, or that there are different versions of the patterns documentation and demos.  That's pretty broken in itself, if you ask me.  Just mentioning "new" certainly was not very clear, given that I do not have the full background or history.

**Comment by fulv** [comment]
It gets worse:  the markup of the demo that's being served at http://patternslib.syslab.com/bumper is different from the one in ploneintranet, and in Patterns (https://github.com/Patternslib/Patterns/blob/master/src/pat/bumper/index.html), and in fact I have no idea how it got there.  It's really hard to work like this.

**Comment by fulv** [comment]
I actually figured out why the http://patternslib.syslab.com/bumper demo is broken:  the main problem is this CSS rule:

    #demo { overflow: auto; }

because then the pattern picks the `div#demo` element as the *scroll container* for the `div.pat-bumper.message.info` bumped element.  But since the `div#demo` element has no scrollbars (because it has auto height), it will never fire the scroll event.

But in reality, I think the `pat-bumper` class should be on the `div#demo` element itself.

Unfortunately, since I don't know where this demo code lives, I can not submit this fix I figured out.

**Comment by fulv** [comment]
Ok, I've fixed the lack of bottom-bumping (https://github.com/Patternslib/Patterns/pull/402).  All the other edges already work.

So with this fix, `pat-bumper` will bump against all edges.  I have not implemented the selector, for which side to bump.  Now that I know how this works, it will be easy, if it's really necessary.

**Comment by cornae** [comment]
@fulv : the pattern supports (or should support) overflow: auto on a parent, otherwise it searches for the next ancestor with overflow: auto and so on to use for the bumper behaviour. If it doesn't find any, it will use the viewport. 

The old demo had a fixed height in CSS, for the new demo there is not yet CSS written.

**Comment by cornae** [comment]
@fulv: Can I have the selector too? If it now responds to all sides by default (default should be 'top') then I run into problems on some existing instances.

@jcbrand: What is the process to go forward now? I have the feeling everybody is waiting for something but I'm not sure what. My goal is to use this pattern in the PI prototype as soon as possible. I'm already waiting many months for this fix and a new deadline is forthcoming :).

**Comment by jcbrand** [comment]
We need to include these fixes in the ploneintranet bundle.

@fulv: Best way to do this is to do a `make clean && make clean-proto` in ploneintranet and run `make jsrelease`.

Then commit and push the dirty LATEST file. It's probably best to do this into a branch and then make a pull request so that Jenkins can have a go at it first. Also double check in `prototype/bundles/` that the latest file has the changes you added.
