### ISSUE TITLE
pat-masonry should recalculate after image loading

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet.prototype#25]
http://demo.ploneintranet.net/search-results-images.html?lemma=min

If you do an image search, the rendering is barfed until you trigger a recalculate by maximizing the window.

**Comment by jcbrand** [comment]
This should be fixed now with the latest bundle release for the proto.

See:
* https://github.com/Patternslib/Patterns/commit/e0b81f4c61ffd108bfbed9d3fae2d40b1f81cd21
* https://github.com/ploneintranet/ploneintranet.prototype/commit/25f9e2d03e261dcddf565324d7b735548c0db060
