### ISSUE TITLE
Search pages should re-use a single search layout

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet.prototype#28]
At the moment, the search contains 5 tabs/quicklinks (representing All, People, Images, Videos, Office). These all share a similar page layout including the search box and quick links at the top and the search results at the bottom.

The way these are currently implemented in the Jekyll prototype is that every page has its own layout in _layouts, and every layout duplicates the HTML for the search box and quick links.

If I've understood things correctly, then all the search pages should instead use a single consistent 'search' layout which defines the common elements, and then each page supplies its own custom HTML for the results. 

This would give two main benefits:

1. Removes the duplication of HTML for the search box and quick links in the prototype
2. Matches the structure of templating engine in the backend, allowing us to stay closer to the prototype when implementing these pages in Plone.

/cc @cornae @jcbrand

**Comment by cornae** [comment]
Hi @mattss , The way the templates and includes are setup in the prototype are not necessarily dictating how it should be set up in the backend templating engine, but could be taking for inspiration at times. The only thing important is that the output HTML will be the same as in proto. So in this case the search box and tabs are present on each search page.

**Comment by mattss** [comment]
@cornae Thanks for the update. If that's the best way to implement it in the prototype, then we can certainly cope with that. I was mainly raising this because it doesn't seem like Jekyll is being used in the way I understand it in this particular case, and I thought that the duplicated html would create more work for you later if it had to change.

**Comment by mattss** [comment]
@gyst I was about to close this, as @cornae has said it is not a concern for him, but then I noticed you assigned me and made this high priority. Was there a specific action you needed out of this, or was it just part of housekeeping?

**Comment by mattss** [comment]
Looks like @cornae has resolved this in https://github.com/ploneintranet/ploneintranet.prototype/commit/0895b46180ea751dac34ff4afa4ee3a7ce801268
