### ISSUE TITLE
Investigate best solution for changing workflow

### ISSUE THREAD

**Issue by jcbrand** [ploneintranet/ploneintranet.prototype#30]
See here: https://github.com/ploneintranet/ploneintranet.prototype/pull/27

> The current way in which pat-select and the workflow dropdown functioned is  not representative to how workflow changing happens in Plone.

> In Plone, you don't have a list of state names to choose from, you have a list
of so-called "transitions" to choose from, and when you choose a transition,
you move from one state to another.

We need to come to a conclusion what to do here. Apparently there is code in StarDesk which shows the end-states for transitions, so we could potentially use that here.

**Comment by gyst** [comment]
This can be done using a option text label (target state) which is different from the option value attribute (transition). Implementation, not design.
