### ISSUE TITLE
Subforms on search results page conflict with one another

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet.prototype#31]
@cornae I've just discovered an issue with the search results page (and found a solution) related to how the subform pattern is used.

The way the search is intended to work (as I understand it) is as follows:
* Typing a search term in the main input starts a brand new search, and completely replaces the bottom part of the page
* Altering the facets on the left-hand-side will submit a modification of the original search and only replace the 'results' page of the page.

The second part of this is achieved by using a pat-subform on the facets and having a hidden copy of the search string embedded in that subform.

The problem arises when you then try and start a brand new search from the main text box, as this re-submits the entire form (including the facets from the previous search), and then replaces the facets part of the page with new ones(!).

The solution I found was to wrap the main search input with another subform, and replicate the data-pat-inject config from the main form onto it as well. This means that starting a new search will ignore any existing facets.

I've made this change temporarily in our search integration fork, but this change needs to go into the prototype as well.

Hope that all makes sense! Let me know if you want to discuss further.

**Comment by mattss** [comment]
Unfortunately my previous solution doesn't actually solve everything, because hitting 'enter' on the main text box overrides the subform autosubmit logic, and submits the entire page. 

My conclusion is that the subform pattern is not the answer here. The top input box and the facet controls should just be completely separate forms in the page, to stop them interfering.

**Comment by cornae** [comment]
Hi Matt, Before we run into all the details in mail form, would it be an idea if I would guide you through the design and the code in a hangout or video? I wasn’t aware you were already coding today.

**Comment by mattss** [comment]
Sounds good @cornae. I will send you an email to follow up.

**Comment by cornae** [comment]
2 solutions suggested during call, moving ticket on to @matts to decide on final solution.

**Comment by mattss** [comment]
Resolving this in implementation by using two separate 'text' field names for each subform.
