### ISSUE TITLE
Expert search

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet.prototype#33]
As a user,
When I search for a topic,
I want to see not only matching documents, but also suggested expert people on this topic, I can contact,
Because often the information I'm looking for may not be written down and live only in somebody's head,
and even if it is written down it may be valuable to ask for input from an expert in the topic area.

**Comment by cornae** [comment]
Currently experts are shown in the search result. They're mixed in with the other results. If this covers it then I can close this ticket. Or would you like changes to this?

**Comment by bfackland** [comment]
Overlaps with #66.
