### ISSUE TITLE
Teamspace: invite

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet.prototype#36]
Teamspace invite interactions are not complete.
Implementation is ahead of design, we need to review how it works and properly design that.

Assembla #257

As a teamspace member,
Given that I have the permission to invite new users into the space,
I want add a new user as a team member,
So I can collaborate with them inside the teamspace.

**Comment by cornae** [comment]
Is 'Add user' insufficient? 

![image](https://cloud.githubusercontent.com/assets/738601/8484749/adc8ed54-20f9-11e5-918f-dd81e2fe5d09.png)

![image](https://cloud.githubusercontent.com/assets/738601/8484752/b3bb7bdc-20f9-11e5-84fb-e64f91d180a9.png)

**Comment by cornae** [comment]
@gyst Is this ticket still current? My last question remained unanswered, hence the ticket is still on my board.

**Comment by gyst** [comment]
Sorry @cornae yes this is OK.
