### ISSUE TITLE
Teamspace: manage role exceptions

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet.prototype#41]
Related to #36
Assembla #370
Role exceptions is only partially designed.

**Comment by reinhardt** [comment]
Is this about the "Change roles" button in the "Members" section of the workspace sidebar? I was going to implement that for ploneintranet/ploneintranet/issues/338 but it seems incomplete. I would expect something like a modal where the user chooses the actual roles.

**Comment by reinhardt** [comment]
@pilz pointed me at http://prototype.ploneintranet.net/feedback/panel-change-role.html.
Will try to use that.

**Comment by cornae** [comment]
I was at this second pushing a fix. See my reference ;)

**Comment by reinhardt** [comment]
Lovely, thank you!

**Comment by reinhardt** [comment]
The text in /feedback/batch-change-roles.html twice mentions removing the users. That seems wrong - we're only changing their roles, aren't we?

"Change the role of the following 2 members to be removed from this workspace. Are you sure? (un-tick to exclude from removing)"

**Comment by reinhardt** [comment]
Sorry for nitpicking, but it still says "exclude from removing". I can't help but feel it should be something like "exclude from the role change".

**Comment by cornae** [comment]
Fixed. I'm happy you pay attention so well, I was so focussed on finding where the (double) appearance of the text was in the code that I became text blind :).

**Comment by reinhardt** [comment]
Super, thank you! (Four eyes see more than two :-))
