### ISSUE TITLE
404 page design

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet.prototype#43]
We need a design for "Not Found" - probably similar to stock Plone with suggestions for "You might be looking for this?"

**Comment by cornae** [comment]
Do you have an example of the "You might be looking for this?" available somewhere where I can grab that HTML?

**Comment by gyst** [comment]
https://plone5.veit-schiele.de/foobar
The ul#page-not-found-list will normally contain multiple suggestions, see screenshot attached.
![404](https://cloud.githubusercontent.com/assets/122351/8351665/6321fbf8-1b2f-11e5-9919-68c5588bec21.png)

**Comment by cornae** [comment]
Thanks!
