### ISSUE TITLE
Textarea under profile photo

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet.prototype#58]
@gyst @cornae Is the purpose of the text area under the profile photo:

http://demo.ploneintranet.net/liz-baker/

for the user to enter their current 'status'? If so, how would this overlap with them writing something in their feed like "Great meeting with the [at]intranet team today"?

![screen shot 2015-05-12 at 10 28 01](https://cloud.githubusercontent.com/assets/2538526/7583929/970e2cd6-f891-11e4-88ec-cba744815a70.png)

**Comment by cornae** [comment]
The latter would a post on the intranet wall or on the wall of a workspace. The status is a different beast. It's like one's status on whatsapp. Some examples of status message can be found here: http://demo.ploneintranet.net/search-results-people.html?lemma=min

One of the message there is outdated. Guido, could you update demo or make it auto update?

**Comment by gyst** [comment]
Yes I plan to update the demo ASAP.

I doubt the usefulness of this status feature as well though. It'll easily become outdated and unlike whatsapp, where your messages are mostly private, our stream is more Twitter like where every statusupdate is actually a status update.

Feature can be dropped IMO.

**Comment by cornae** [comment]
Agreed. I removed it. We can use the line for another kind of status in future if we like. Like 'Last logged in …' or similar.

**Comment by gyst** [comment]
On 02/07/15 20:44, Cornelis G. A. Kolbach wrote:
> Agreed. I removed it. We can use the line for another kind of status in
> future if we like. Like 'Last logged in …' or similar.

Yes I saw that the main thing you used this for, is for "out of office"
statuses. "Last logged in ..." or "Last activity ..." suffices for that
and is actually less error prone.

:*CU#
-- 
    Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

    s o c i a l   k n o w l e d g e   t e c h n o l o g y
