### ISSUE TITLE
Follow / Unfollow toggle on user profile

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet.prototype#59]
As a User
**I can follow another user**
in order to keep up-to-date with the posts they make and opinions they share within the intranet environment.

As a User
**I can unfollow a user I am already following**
if I no longer wish to keep up-to-date with the posts they make.

I suggest this is primarily toggled when viewing another user's profile:

http://demo.ploneintranet.net/jeff-peters/

I also suggest there is a quick option to follow people who are already following me:

http://demo.ploneintranet.net/liz-baker/#person-followers

and unfollow people who I am already following:

http://demo.ploneintranet.net/liz-baker/#person-following

FYI @mattss @gyst

**Comment by cornae** [comment]
The 2 user stories mentioned above are already solutioned in the prototype. 

"I also suggest there is a quick option to follow people who are already following me:" sounds like a nice addition. Could we put that in a separate ticket, rather than keeping this umbrella ticket?

"unfollow people who I am already following" sounds like an unfollow all. Why would we like to have that feature? It seems social suicide to me, but maybe there's a benefit I don't see yet. Either way, could we have this one also in a separate ticket, then we can close this ticket.

**Comment by bfackland** [comment]
> "I also suggest there is a quick option to follow people who are already following me:" sounds like a nice addition. Could we put that in a separate ticket, rather than keeping this umbrella ticket?

Done: #64 

> "unfollow people who I am already following" sounds like an unfollow all. Why would we like to have that feature? It seems social suicide to me, but maybe there's a benefit I don't see yet. Either way, could we have this one also in a separate ticket, then we can close this ticket.

Not "unfollow all" - we don't want to encourage that! I was proposing a button on each row of the listing so I can quickly unfollow people I am bored with, similar to Twitter when you are logged in:

https://twitter.com/following

However I now question whether we want to make this easy for users. It might be better if they have to follow a link to a full profile in order to then unfollow someone..?

**Comment by cornae** [comment]
> Not "unfollow all" - we don't want to encourage that! I was proposing a button on each row of the listing so I can quickly unfollow people I am bored with, similar to Twitter when you are logged in:
> 
> https://twitter.com/following

Ahh, like that it makes a lot more sense :). 

> However I now question whether we want to make this easy for users. It might be better if they have to follow a link to a full profile in order to then unfollow someone..?

That's an interesting one. It might be one of those stories that we want to introduce once people are asking for it.

**Comment by bfackland** [comment]
> It might be one of those stories that we want to introduce once people are asking for it.

Agreed. Closing this umbrella issue.
