### ISSUE TITLE
Show "my group memberships" on profile page?

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet.prototype#60]
@gyst @cornae @mattss We discussed indicating which team spaces a user is a member of on their profile page. (One would assume that we only show team spaces that the profile viewer can see.) I don't recall Netsight doing this on any of it's other intranets/portals, although I can see some value in it. Where did this requirement come from? Is it a priority for Venus?

**Comment by bfackland** [comment]
Looks like this is already being worked on in #38.

**Comment by gyst** [comment]
Yes, duplicates #38, closing.
