### ISSUE TITLE
Include "did you mean" spelling suggestion in search prototype UI

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet.prototype#65]
We concluded that we should include "did you mean" in the UI prototype, even if it does not get implemented for Venus.

As a User
**if I type a search term that looks (or sounds) like it is misspelt, a correct spelling should be suggested**
so that I can avoid missing the search results I might have been looking for.

http://demo.ploneintranet.net/search-results.html

This has a dependency on the search engine functionality and suitable dictionaries being available.

**Comment by cornae** [comment]
Overlap with #49 ?

**Comment by bfackland** [comment]
Ah yes - not that familiar with what already exists. Will try and avoid duplicates.

Although I also have a user story :)

**Comment by cornae** [comment]
You do indeed have a user story and I love those :)
