### ISSUE TITLE
pat-inject + pat-autosubmit explodes

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet.prototype#74]
While working on
https://github.com/ploneintranet/ploneintranet/pull/216
I noticed that the first "like" on a statusupdate works fine, but if you then, without a reload, click the "unlike" and look at your network console you see @@toggle-like gets hit two times. The next click triggers 4 hits, after that 8 etc.

This behavior is already there on master before merging the pull request.
I've debugged the backend to the hilt and can see no explanation for this behavior in the backend.
Most likely candidate therefore is some weirdness in the ajax layer.

**Comment by jcbrand** [comment]
This should be fixed now. I've created a [pull request](https://github.com/ploneintranet/ploneintranet/pull/291).

There was a subtle bug that spanned pat-inject and the patterns registry which should now be fixed.
