### ISSUE TITLE
Remove dead-end hyperlinks on "Apps" tab

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet.prototype#79]
I'd like to demo the prototype to a potential customer in the near future and I'm concerned with the dead-end links on the "Apps" tab:

http://prototype.ploneintranet.net/apps.html

For apps that aren't yet available my suggestion would be that the block is greyed-out and not click-able, e.g. Contacts, Calendar, Slide bank etc.

**Comment by bfackland** [comment]
@mattss FYI.
@cornae @pilz what do you think?

**Comment by pilz** [comment]
Either that - or linking to a coming soon page. I am fine with everything.

**Comment by gyst** [comment]
+1 for "coming soon"

**Comment by cornae** [comment]
Both greyed out (class `disabled`) and a coming soon page. I'll put the ticket on my name to design both. A q&d temp solution is to put a .js alert on it with the coming soon message.

**Comment by bfackland** [comment]
Sounds great - thanks.

On 24 Jun 2015, at 10:57, Cornelis G. A. Kolbach <notifications@github.com> wrote:

> Both greyed out (class disabled) and a coming soon page. I'll put the ticket on my name to design both. A q&d temp solution is to put a .js alert on it with the coming soon message.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

--
Ben Ackland, Projects Director
Netsight Internet Solutions Limited
Tel: +44 (0)117 90 90 90 1

Registered in England no. 3892180
Registered office: 40 Berkeley Square, Bristol, BS8 1HU, United Kingdom

**Comment by bfackland** [comment]
Thanks.
