### ISSUE TITLE
"create workspace" modal dialog

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet.prototype#80]
In the Plone implementation, in /workspaces.html we have a button "create workspace" that is not in the prototype. We need the functionality but it needs to be slick.

Any workspace one creates has security settings. Currently those are buried 2 click levels deep in settings/security. Which means users creating a workspace get the default settings which are the most secure possible, which is generally not what you want. We cannot change the default settings without compromising security.

Instead, the solution would be that "create workspace" triggers a modal dialog that lets you select from 3 pre-defined security policies:
[ ] completely locked down secret workspace (a)
[*] self-managed private teamspace (default) (b)
[ ] open community (c)
And an extra option:
[ ] custom settings

The settings are those exposed in http://demo.ploneintranet.net/feedback/workspace-settings-security.html

Option (a) = secret + admin-managed + produce
Option (b) = private + team-managed + publish
Option (c) = open + self-managed + publish

Option (d) would then allow you to change the security sliders.

Then, after selecting the security you go ahead, input a title and create the workspace.
Ideally, that would land you in the workspace with the "general settings" panel open.

**Comment by cornae** [comment]
Exactly how I had it in mind, with the exception that option (d) is a nifty addition that I hadn't thought of. 

We might want to consider to make option (d) a separate ticket, since it's probably more work on itself than the whole basic feature without it.

**Comment by pilz** [comment]
Interesting is also how to create Cases. Will there be either a "workspace type" option or a complete separate "Add case" entry point?

**Comment by cornae** [comment]
Probably the best solution

**Comment by gyst** [comment]
On 23/05/15 22:35, Cornelis G. A. Kolbach wrote:
> Probably the best solution
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ploneintranet/ploneintranet.prototype/issues/80#issuecomment-104943260>.
> 

See also my rewording in
https://github.com/ploneintranet/ploneintranet/commit/83e65dd719e9a8b4ed79b50024f6aaa7951bac97#commitcomment-11380668

-- 
    Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

    s o c i a l   k n o w l e d g e   t e c h n o l o g y
