### ISSUE TITLE
Modal height not recalculated

### ISSUE THREAD

**Issue by cornae** [ploneintranet/ploneintranet.prototype#81]
The modal height doesn't recalculate after pat-depends events on the modal and possibly also other layout modifiers. 

To reproduce, open '/feedback/panel-create-workspace.html' and toggle between the radio buttons.

**Comment by gyst** [comment]
@jcbrand if you can fix this easily it would help Cornelis a lot

**Comment by jcbrand** [comment]
@gyst Not sure how much work it is. The modal positioning code is relatively hairy and fragile due to browser differences. Also, whether I can work on this depends on whether I'm assigned time for it or not.

**Comment by cornae** [comment]
Is there a way you can let modal also listen to layout modifiers just like we do with other patterns, and let it rerun its height calc function?

**Comment by jcbrand** [comment]
@cornae: Yes, that would be the solution. I realise now that this issue is not about the modal being positioned or resized wrongly, but just that it doesn't update. That's much simpler to fix. Probably an hour or two.

**Comment by cornae** [comment]
I was so much hoping that would be the answer ;)
