### ISSUE TITLE
Design the additional metadata form for Case objects

### ISSUE THREAD

**Issue by cillianderoiste** [ploneintranet/ploneintranet.prototype#88]

**Comment by cornae** [comment]
@pilz, Is this what we were going to solve with the pre-populated rich pages?

**Comment by pilz** [comment]
That was the metadata form that we added into the sidebar settings. Now it is in question whether that is the right place for the importance of the data. The pre-populated rich pages are an approach to solve that, we will have another discussion on this tomorrow.

**Comment by cornae** [comment]
Currently any action from me required here? Otherwise I'll close the issue.
