### ISSUE TITLE
Crop portrait images to ensure they are square

### ISSUE THREAD

**Issue by cillianderoiste** [ploneintranet/ploneintranet.prototype#90]
ploneintranet/ploneintranet#84
I investigated this, and it's not trivial to crop the profile images server side. Can you take care of it client side?

**Comment by cornae** [comment]
@gyst I can do that, but it has an influence on my planning as well as on the elegance of the front end code. I have to create a solution throughout the application, everywhere we have avatars. That is a in a lot of places. And this solution comprises also markup which has to be ported to dev again and then again checked by me. I think it will be anywhere between 2 and 8 hours for me, so also not trivial. And then it would still be a dirty monkey patch.Ultimately we should have a server side solution anyway. Is there any capacity available in the dev teams?

**Comment by cornae** [comment]
@gyst, Have you made a decision on this?

**Comment by mattss** [comment]
@cillianderoiste probably worth noting that with membrane profiles, profile images will likely be blob fields on DX content so should be resizable with plone.app.imaging

**Comment by cornae** [comment]
Any news on this? It's still on my name, but I feel there's nothing I can do at this moment.

**Comment by mattss** [comment]
Along with https://github.com/ploneintranet/ploneintranet/issues/84, i'm pretty sure this was fixed by https://github.com/ploneintranet/ploneintranet/pull/301

**Comment by gyst** [comment]
I responded to this yesterday, but apparently that got lost.

Cropping needs to happen both server side and in the browser, which is
why it's still on your name.

It needs to happen on the server so we have minimal sanity. That's out
of your scope obviously.

It needs to happen in the browser so the user controls the crop and can
do the "face detection" .

**Comment by gyst** [comment]
Ah damn I'm now only seeing Cornelis' initial reply. Yes cancelled.
