### ISSUE TITLE
Search - filter by 'Last modified' or 'created'?

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet.prototype#93]
The search page used to have a 'created' filter, but this has recently been changed to the label 'last modified'. However the options available still include 'Any creation date' as the default.

See: http://prototype.ploneintranet.net/search-results.html

Can I clarify which date we are providing a filter for?

**Comment by mattss** [comment]
Not sure if this is a question for @cornae or @gyst

**Comment by cornae** [comment]
I think I designed with created first, but later we changed to modified. That's correct, isn't it @gyst? I haven't updated the word created to 'modified' yet in the options. Well spotted :)
