### ISSUE TITLE
Inconsistent markup of user profile search results

### ISSUE THREAD

**Issue by adrianwhite** [ploneintranet/ploneintranet.prototype#94]
@cornae  the title attribute on the data information on profiles in the search results is inconsistent.

https://github.com/ploneintranet/ploneintranet.prototype/blob/master/_layouts/search-people.html#L32-L39

    <ul class="data">
        <li class="mail icon-mail">
            <a title="Mail Minoush at minoush.farmer@organisation.com" href="mailto:minoush.farmer@organisation.com">minoush.farmer@organisation.com</a>
        </li>
        <li title="Call Minoush at +34 506 948 294" class="phone icon-phone">
            <a href="tel:+34506948294">+34 506 948 294</a>
        </li>
    </ul>
Should the title attribute be on the `<li>` or on the `<a>` ?

**Comment by cornae** [comment]
Either is fine, lets put it on the a.

**Comment by adrianwhite** [comment]
Will do.

**Comment by adrianwhite** [comment]
Fixed in 78c7a1253895045b6509949e5ae55db6a30e9927
