### ISSUE TITLE
Combining all/none filters with pat-autosubmit generates multiple requests

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet.prototype#95]
The combination of the auto-submit filters on the search form and the all/none toggles means that the form can generate a *lot* of useless search requests to the backend.

Example, go here on the prototype, open your XHR console and click 'None' next to 'content types'.
http://prototype.ploneintranet.net/search-results.html?SearchableText=asdf&submit=submit

You should see *ten* requests fire off (one for each checkbox). The user must wait for them all to complete before selecting the checkbox they actually want, otherwise race condition issues can result in unexpected results being displayed.

**Comment by cornae** [comment]
Does it help to put a delay of only 100ms or so? There's a property for that.

**Comment by mattss** [comment]
Unfortunately adding pat-autosubmit delay just delays the submission of the requests, without reduce the number of them.

**Comment by cornae** [comment]
Pity. Then it's out of my control. Perhaps @jc has some ideas.

**Comment by mattss** [comment]
This was resolved by https://github.com/ploneintranet/ploneintranet/pull/340, although it may also have introduce #106
