### ISSUE TITLE
It should be possible to limit a search-wide search to the current section (before submitting)

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet.prototype#96]
As a User
**I want to limit the search I am about to perform to the current Workspace (or other major section)**
so that I can restrict the scope of my results to the area I am working in.

In standard Plone this is implemented as a checkbox next to the site-wide search field "Only search this [Type Name]". This checkbox is not shown if the user is outside of a specific section.

Technical note: sections should be registered somehow (e.g. the system should know that a Workspace is a section).

**Comment by bfackland** [comment]
@mattss @pilz FYI.

**Comment by pilz** [comment]
The plone approach by folder is very generic. It might be enough to hardcode the search on a workspace to limit to the workspace. To not allow limiting to folders below, as this is probably too specific to understand and not to offer any limitations for any other section of the site. 

Then on the search results, it could state that this is a resultset limited to the current workspace and that you can broaden your search to a global one.

**Comment by bfackland** [comment]
That sounds sensible.

I'd suggest we store a list somewhere of container types that can act as search anchors/roots, initially just 'Workspace'. I imagine this might also be useful (for instance) in the Library section/app.

**Comment by cornae** [comment]
In our vision of search, we wouldn't have advanced search, but rather work with filters after entering the search term. This box is a form of advanced search. I think it doesn't fit very well, albeit that the use case is very valid imo. At Informaat we had implemented this box exactly like this in the intranet and it resulted in problems: People didn't understand what the exact scope was of the box. "It's a global search isn't it? What does this section mean then? This workspace, this folder, or even just this document I'm viewing?" Technical issues there were as well. Parts of the screen were updated by means of injection and the search box didn't 'know' about that. 

I think we should solve the narrowed scope search use case with dedicated search boxes that are placed in context. One we already have: the search box in the sidebar of a workspace, which solves it already for workspaces. In the future contacts app there will be a search box too. I have one in minde for the Workspaces screen that only gives workspaces back. etc.

**Comment by gyst** [comment]
So the question is for a specific use case. Searching in workspaces is already supported. A different section search requires a different search page design for that section.

**Comment by bfackland** [comment]
OK, I understand the proposal that we should implement section-specific searches. @gyst Is it currently possible to initiate a search from a Workspace that is limited to that scope? I don't see that in the prototype.

@cornae Where would you envisage a document-specific search being presented in the Library? http://prototype.ploneintranet.net/library.html -- Presumably it makes sense for us to come up with a consistent, familiar representation of context-specific search in the UI.

**Comment by cornae** [comment]
> Op 24 jun. 2015, om 21:42 heeft Ben Ackland <notifications@github.com> het volgende geschreven:
> 
> OK, I understand the proposal that we should implement section-specific searches. @gyst Is it currently possible to initiate a search from a Workspace that is limited to that scope? I don't see that in the prototype.

Wow you’re right, it’s currently not there. I think it disappeared a while ago with an update to item-selector because it is in the code of item selector. I’ll look into that.

> @cornae Where would you envisage a document-specific search being presented in the Library? http://prototype.ploneintranet.net/library.html -- Presumably it makes sense for us to come up with a consistent, familiar representation of context-specific search in the UI.

On the ‘canvas toolbar’. For Library, Workspaces and apps alike. Once it’s in the backlog.

**Comment by cornae** [comment]
>> OK, I understand the proposal that we should implement section-specific searches. @gyst Is it currently possible to initiate a search from a Workspace that is limited to that scope? I don't see that in the prototype.
> 
> Wow you’re right, it’s currently not there. I think it disappeared a while ago with an update to item-selector because it is in the code of item selector. I’ll look into that.

Search field is back now.
